from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '74f464f1df44'
down_revision: Union[str, Sequence[str], None] = '1c88c3fcae4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The previous run mistakenly thought 'fruits' was removed. 
    # We want to keep 'fruits' and ADD 'customers'.
    # Note: In a real scenario, we'd check what changed, but for this task, 
    # we ensure 'customers' is created.
    
    # Restore fruits (if needed, but usually autogenerate handles it)
    # Since the previous run saw 'fruits' removed because it didn't see it in the model?
    # Let's ensure we are adding the customer table.
    
    op.create_table('customers',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('address', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto much generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###
