"""last_attempt_to_see_what_is_missing

Revision ID: 9250f5b51ede
Revises: 9f69f9526aa6
Create Date: 2026-04-22 20:40:55.136798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9250f5b51ede'
down_revision: Union[str, Sequence[str], None] = '9f69f9526aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
