"""fix_the_empty_migrations_manually

Revision ID: 9f69f9526aa6
Revises: fc1f614311ae
Create Date: 2026-04-22 20:40:49.136281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f69f9526aa6'
down_revision: Union[str, Sequence[str], None] = 'fc1f614311ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
